name: Check linters

on:
  push:
    branches: [ docker_devops_assignment ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r app/requirements.txt
      - name: Run linter
        run: flake8 app
  build_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          cd ./app
          docker build --build-arg DEPLOY_REF=${{ github.sha }} -t ghcr.io/${{ github.repository_owner }}/check-assignment-tests:${{ github.sha }} .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/check-assignment-tests:${{ github.sha }}
